FROM apache/airflow:3.3.1

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    "pyspark==4.2.0" \
    "apache-airflow-providers-apache-spark==6.3.2"

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64